### ISSUE TITLE
java.lang.IllegalStateException: Failed to introspect annotations

### ISSUE THREAD

**Issue by chornyi** [spring-cloud-samples/zuul-server#4]
To reproduce:

1. Checkout https://github.com/spring-cloud-samples/zuul-server
2. Replace @EnableZuulProxy with @EnableZuulServer in ZuulServerApplication.java.
3. Package the application using `mvn package` 
4. Execute using `java -jar .\zuul-server-1.0.0.BUILD-SNAPSHOT.jar`

         java.lang.IllegalStateException: Failed to introspect annotations: class zuulserver.ZuulServerApplication
			at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:166)
			at org.springframework.core.annotation.AnnotatedElementUtils.isAnnotated(AnnotatedElementUtils.java:73)
			at org.springframework.core.type.StandardAnnotationMetadata.isAnnotated(StandardAnnotationMetadata.java:102)
			at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:74)
			at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:64)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:140)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:127)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.register(AnnotatedBeanDefinitionReader.java:122)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:159)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:135)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:127)
			at org.springframework.boot.SpringApplication.load(SpringApplication.java:620)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
			at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
			at zuulserver.ZuulServerApplication.main(ZuulServerApplication.java:21)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
			at java.lang.reflect.Method.invoke(Unknown Source)
			at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
			at java.lang.Thread.run(Unknown Source)
			Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
			at sun.reflect.annotation.AnnotationParser.parseClassArray(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseArray(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseMemberValue(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotation2(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotations2(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotations(Unknown Source)
			at java.lang.Class.createAnnotationData(Unknown Source)
			at java.lang.Class.annotationData(Unknown Source)
			at java.lang.Class.getAnnotations(Unknown Source)
			at org.springframework.core.annotation.AnnotatedElementUtils.doProcess(AnnotatedElementUtils.java:192)
			at org.springframework.core.annotation.AnnotatedElementUtils.doProcess(AnnotatedElementUtils.java:209)
			at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:162)
			... 20 common frames omitted
			java.lang.reflect.InvocationTargetException
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
			at java.lang.reflect.Method.invoke(Unknown Source)
			at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
			at java.lang.Thread.run(Unknown Source)
			Caused by: java.lang.IllegalStateException: Failed to introspect annotations: class zuulserver.ZuulServerApplication
			at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:166)
			at org.springframework.core.annotation.AnnotatedElementUtils.isAnnotated(AnnotatedElementUtils.java:73)
			at org.springframework.core.type.StandardAnnotationMetadata.isAnnotated(StandardAnnotationMetadata.java:102)
			at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:74)
			at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:64)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:140)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.registerBean(AnnotatedBeanDefinitionReader.java:127)
			at org.springframework.context.annotation.AnnotatedBeanDefinitionReader.register(AnnotatedBeanDefinitionReader.j:122)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:159)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:135)
			at org.springframework.boot.BeanDefinitionLoader.load(BeanDefinitionLoader.java:127)
			at org.springframework.boot.SpringApplication.load(SpringApplication.java:620)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
			at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139)
			at zuulserver.ZuulServerApplication.main(ZuulServerApplication.java:21)
			... 6 more
			Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
			at sun.reflect.annotation.AnnotationParser.parseClassArray(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseArray(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseMemberValue(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotation2(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotations2(Unknown Source)
			at sun.reflect.annotation.AnnotationParser.parseAnnotations(Unknown Source)
			at java.lang.Class.createAnnotationData(Unknown Source)
			at java.lang.Class.annotationData(Unknown Source)
			at java.lang.Class.getAnnotations(Unknown Source)
			at org.springframework.core.annotation.AnnotatedElementUtils.doProcess(AnnotatedElementUtils.java:192)
			at org.springframework.core.annotation.AnnotatedElementUtils.doProcess(AnnotatedElementUtils.java:209)
			at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:162)
			... 20 more

**Comment by spencergibb** [comment]
I'm unable to reproduce with your provided steps.  What OS, java version and mvn version are you using?

**Comment by chornyi** [comment]
Java 1.8.0_25
Maven: 3.2.1
Windows 7 x64

I also had same result on Ubuntu (both building and running).

Here is a branch where I just was able to reproduce: https://github.com/chornyi/zuul-server/tree/issue_4

I also added a jar: https://github.com/chornyi/zuul-server/blob/issue_4/zuul-server-1.0.0.BUILD-SNAPSHOT.jar

Thanks for looking into this.

**Comment by AnandKSingh** [comment]
@chornyi @spencergibb  did you guys found a solution for this?

**Comment by spencergibb** [comment]
This 2.5 year old commit 58b0f46

**Comment by RaviShekhawat** [comment]
Hi Guys I'm facing this issue in a SpringBoot project of mine: Error creating bean with name 'restTemplateBuilder' defined in class path resource [org/springframework/boot/autoconfigure/web/client/RestTemplateAutoConfiguration.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [org.springframework.boot.web.client.RestTemplateBuilder] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@4f8e5cde].

Can somebody please help me here?

**Comment by spencergibb** [comment]
@RaviShekhawat please don't comment on old closed issues. Ask in the spring boot gitter channel

**Comment by RaviShekhawat** [comment]
@spencergibb Sir I'm bit new to this Q&A thing. Gotta create something really useful in SpringBoot. Can you please guide me about gitter channel? How to access it and all?

**Comment by spencergibb** [comment]
NP https://gitter.im/spring-projects/spring-boot
