### ISSUE TITLE
Error when running the samples

### ISSUE THREAD

**Issue by kabennett** [spring-cloud-samples/zuul-server#6]
I am running the zuul server, eureka server, and stores samples.  I am receiving the error 'Host name may not be null' when I hit http://localhost:8765/stores.  I can hit http://localhost:8081/simple/stores just fine.  Not sure what is wrong here.
```
com.netflix.zuul.exception.ZuulException: Forwarding error
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:146)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:110)
	at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112)
	at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:197)
	at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:161)
	at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:120)
	at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:84)
	at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:111)
	at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:77)
	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:158)
	at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequestInternal(ZuulController.java:43)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:146)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:943)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130)
	at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:291)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:102)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.netflix.hystrix.exception.HystrixRuntimeException: storesRibbonCommand failed and no fallback available.
	at com.netflix.hystrix.AbstractCommand$20.call(AbstractCommand.java:816)
	at com.netflix.hystrix.AbstractCommand$20.call(AbstractCommand.java:798)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.Observable$ThrowObservable$1.call(Observable.java:9058)
	at rx.Observable$ThrowObservable$1.call(Observable.java:9048)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:78)
	at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:318)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:310)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:78)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
	at com.netflix.hystrix.AbstractCommand$HystrixObservableTimeoutOperator$3.onError(AbstractCommand.java:995)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.Observable$ThrowObservable$1.call(Observable.java:9058)
	at rx.Observable$ThrowObservable$1.call(Observable.java:9048)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:78)
	at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:301)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:293)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:388)
	at com.netflix.hystrix.AbstractCommand$1.call(AbstractCommand.java:368)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1097)
	at com.netflix.hystrix.AbstractCommand$ObservableCommand$1.call(AbstractCommand.java:1093)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.subscribe(Observable.java:7393)
	at rx.internal.operators.BlockingOperatorToFuture.toFuture(BlockingOperatorToFuture.java:57)
	at rx.observables.BlockingObservable.toFuture(BlockingObservable.java:409)
	at com.netflix.hystrix.HystrixCommand.queue(HystrixCommand.java:385)
	at com.netflix.hystrix.HystrixCommand.execute(HystrixCommand.java:339)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:130)
	... 63 common frames omitted
Caused by: com.netflix.client.ClientException: Number of retries on next server exceeded max 1 retries, while making a call for: stores:8081
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$4.call(LoadBalancerCommand.java:350)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$4.call(LoadBalancerCommand.java:345)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onError(OperatorOnErrorResumeNextViaFunction.java:77)
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1$1.onError(OperatorRetryWithPredicate.java:100)
	at rx.observers.SerializedObserver.onError(SerializedObserver.java:122)
	at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:65)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onError(OperatorConcat.java:134)
	at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onError(OperatorConcat.java:204)
	at rx.observers.SerializedObserver.onError(SerializedObserver.java:122)
	at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:65)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onError(OperatorConcat.java:134)
	at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onError(OperatorConcat.java:204)
	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
	at rx.Observable$ThrowObservable$1.call(Observable.java:9058)
	at rx.Observable$ThrowObservable$1.call(Observable.java:9048)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:163)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:128)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:65)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:41)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:30)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:163)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:128)
	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onNext(OperatorConcat.java:65)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:185)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.unsafeSubscribe(Observable.java:7304)
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:112)
	at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:81)
	at rx.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:59)
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:77)
	at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:41)
	at rx.internal.util.ScalarSynchronousObservable$1.call(ScalarSynchronousObservable.java:30)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable$1.call(Observable.java:145)
	at rx.Observable$1.call(Observable.java:137)
	at rx.Observable.subscribe(Observable.java:7393)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:441)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:340)
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:102)
	at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:81)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand.forward(RibbonCommand.java:129)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand.run(RibbonCommand.java:103)
	at org.springframework.cloud.netflix.zuul.filters.route.RibbonCommand.run(RibbonCommand.java:48)
	at com.netflix.hystrix.HystrixCommand$1.call(HystrixCommand.java:298)
	... 106 common frames omitted
Caused by: com.sun.jersey.api.client.ClientHandlerException: java.lang.IllegalArgumentException: Host name may not be null
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:184)
	at com.sun.jersey.api.client.Client.handle(Client.java:648)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:507)
	at com.netflix.niws.client.http.RestClient.execute(RestClient.java:618)
	at com.netflix.niws.client.http.RestClient.execute(RestClient.java:527)
	at com.netflix.niws.client.http.RestClient.execute(RestClient.java:92)
	at com.netflix.client.AbstractLoadBalancerAwareClient$1.call(AbstractLoadBalancerAwareClient.java:109)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:303)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$3$1.call(LoadBalancerCommand.java:287)
	... 147 common frames omitted
Caused by: java.lang.IllegalArgumentException: Host name may not be null
	at org.apache.http.util.Args.notBlank(Args.java:65)
	at org.apache.http.HttpHost.<init>(HttpHost.java:81)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.getHost(ApacheHttpClient4Handler.java:190)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170)
	... 157 common frames omitted

2015-11-13 11:03:07.572 DEBUG 11296 --- [  XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : DispatcherServlet with name 'dispatcherServlet' processing GET request for [/error]
2015-11-13 11:03:07.573 DEBUG 11296 --- [  XNIO-1 task-2] s.w.s.m.m.a.RequestMappingHandlerMapping : Looking up handler method for path /error
2015-11-13 11:03:07.573 DEBUG 11296 --- [  XNIO-1 task-2] s.w.s.m.m.a.RequestMappingHandlerMapping : Returning handler method [public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)]
2015-11-13 11:03:07.573 DEBUG 11296 --- [  XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : Last-Modified value for [/error] is: -1
2015-11-13 11:03:07.574 DEBUG 11296 --- [  XNIO-1 task-2] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : Written [{timestamp=Fri Nov 13 11:03:07 CST 2015, status=500, error=Internal Server Error, exception=com.netflix.zuul.exception.ZuulException, message=Forwarding error}] as "application/json;charset=UTF-8" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@35b2f8b]
2015-11-13 11:03:07.574 DEBUG 11296 --- [  XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2015-11-13 11:03:07.574 DEBUG 11296 --- [  XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : Successfully completed request
2015-11-13 11:03:07.575 DEBUG 11296 --- [  XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : Null ModelAndView returned to DispatcherServlet with name 'dispatcherServlet': assuming HandlerAdapter completed request handling
2015-11-13 11:03:07.575 DEBUG 11296 --- [  XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : Successfully completed request
2015-11-13 11:03:25.441  INFO 11296 --- [pool-4-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_ZUULSERVER/INFO_KL-BGQFCT1 - Re-registering apps/ZUULSERVER
2015-11-13 11:03:25.441  INFO 11296 --- [pool-4-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_ZUULSERVER/INFO_KL-BGQFCT1: registering service...
2015-11-13 11:03:25.458  INFO 11296 --- [pool-4-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_ZUULSERVER/INFO_KL-BGQFCT1 - registration status: 204
2015-11-13 11:03:35.430  INFO 11296 --- [scoveryClient-2] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_ZUULSERVER/INFO_KL-BGQFCT1 - retransmit instance info with status UP
2015-11-13 11:03:35.431  INFO 11296 --- [scoveryClient-2] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_ZUULSERVER/INFO_KL-BGQFCT1: registering service...
2015-11-13 11:03:35.436  INFO 11296 --- [scoveryClient-2] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_ZUULSERVER/INFO_KL-BGQFCT1 - registration status: 204
2015-11-13 11:03:55.465  INFO 11296 --- [pool-4-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_ZUULSERVER/INFO_KL-BGQFCT1 - Re-registering apps/ZUULSERVER
2015-11-13 11:03:55.465  INFO 11296 --- [pool-4-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_ZUULSERVER/INFO_KL-BGQFCT1: registering service...
2015-11-13 11:03:55.470  INFO 11296 --- [pool-4-thread-1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_ZUULSERVER/INFO_KL-BGQFCT1 - registration status: 204
2015-11-13 11:04:25.452  INFO 11296 --- [pool-5-thread-1] o.s.c.n.zuul.web.ZuulHandlerMapping      : Mapped URL path [/zuulserver/**] onto handler of type [class org.springframework.cloud.netflix.zuul.web.ZuulController]
```

**Comment by kabennett** [comment]
Really, I am just looking for a simple code example that demonstrates the minimal configuration to run a standalone edge server (via Spring Cloud Zuul), discovery server (via Spring Cloud Eureka), and a simple service (like Hello World...I don't care what the service does).  After I have this working, I'd like to integrate Hystrix as well.  Can anyone point me to such a reference implementation?

**Comment by zunelewin** [comment]
you can check it out in this link https://github.com/callistaenterprise/blog-microservices/tree/B1/microservices..
